apiVersion: 1

datasources:
  - name: opensearch-cluster
    uid: opensearch
    type: elasticsearch
    access: proxy
    url: http://opensearch-cluster:9200
    editable: true
    isDefault: false
    jsonData:
      interval: 'No Pattern'
      timeField: '@timestamp'
      esVersion: '8.0.0'
      logMessageField: _source
      logLevelField: Attributes.levelname
      dataLinks:
        - datasourceUid: webstore-traces
          field: Attributes.trace_id
          url: '$${__value.raw}'

